workflows:
  expo_ios:
    name: Build iOS Expo App
    max_build_duration: 60
    environment:
      node: 18
      cocoapods: default
      # optional: cache npm and pods
      cache:
        paths:
          - ~/.npm
          - ios/Pods
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli@latest
          npm install
      - name: Build iOS
        script: |
          eas build -p ios --non-interactive
    artifacts:
      - '**/*.ipa'
